Handle resize events [Feature request #196]
LemonBoy/bar pull request #197
Opened 2016-12-30 23:58 UTC by dan-santana

Implements resize events handling as requested in #196.

2017-01-02 19:55 UTC, LemonBoy requested changes
Not to sure about this as we do some trickery during the setup phase wrt the geometry and the monitor chains.

2017-01-02 19:55 UTC, LemonBoy commented on lemonbar.c
> +};
Let's just add a `NET_WM_ATOM_MAX` to avoid the `sizeof/sizeof` repeated twice.

2017-01-02 19:55 UTC, LemonBoy commented on lemonbar.c
> +    if (mon->pixmap) {
No brackets on 1-line `if`s.

2017-01-02 19:55 UTC, LemonBoy commented on lemonbar.c
> +                                if (mon->window != notify_ev->window)
Once the matching `window` is processed you can terminate the loop.

2017-01-02 19:55 UTC, LemonBoy commented on lemonbar.c
> +    if (!atom_list[0])
Is a `xcb_atom_t` type nullable?

2017-01-02 19:55 UTC, LemonBoy commented on lemonbar.c
> +                                create_pixmap(mon); // Xorg doesn't allow resizing pixmaps, so we create a new one
Put the comment above the code so that the lines are not too long.

2017-02-20 16:01 UTC, dan-santana commented
Indeed, this solution would make more sense if bar geometries were not dinamically set by default. 

Particularly, it feels a bit hackish as some agreed in https://github.com/LemonBoy/bar/issues/163, maybe a sane approach would be to split the bar in two scripts, keeping only the manual geometry logic set by `-g` in `lemonbar`, and moving the Randr/Xinerama magic into a helper script (`lemonbar-multihead`?) that parses the `{S*}` blocks, creates a bar for each monitor and sends the relevant part of the input to each one. Then https://github.com/LemonBoy/bar/pull/171 would make sense again too.

Anyway, should this PR be closed? I don't feel that it makes sense too, in the current state of the project.

2021-11-23 02:01 UTC, VentGrey commented
Any updates on this?

2026-03-31 02:10 UTC, closed without merging